MFLAGS=-AC99 +DD64 -DC99 -DMEM_DEBUG

all: libdmemory.sl test.c
	$(CC) $(MFLAGS) test.c -g -otest -L. -I. -ldmemory

libdmemory.sl: dmemory.o list.o exceptions.o
	$(CC) $(MFLAGS) -b -o $@ $?

dmemory.o: dmemory.c dmemory.h debug.h
	$(CC) $(MFLAGS) -g +z -c $<

list.o: list.c list.h
	$(CC) $(MFLAGS) -g +z -c $<

exceptions.o: exceptions.c exceptions.h
	$(CC) $(MFLAGS) -g +z -c $<

clean:
	rm -f dmemory.o list.o exceptions.o libdmemory.sl test.o test

