MFLAGS=-DC99 -DMEM_DEBUG -gdwarf-2 -g3

all: libdmemory.so test.c
	$(CC) test.c -g -otest -ldmemory -L. $(MFLAGS)

libdmemory.so: dmemory.o list.o exceptions.o
	$(CC) -shared -Wl,-soname,$@ -o $@ $? $(MFLAGS)

dmemory.o: dmemory.c dmemory.h debug.h
	$(CC) -fPIC $(MFLAGS) -g -c $<

list.o: list.c list.h
	$(CC) -fPIC $(MFLAGS) -g -c $<

exceptions.o: exceptions.c exceptions.h
	$(CC) -fPIC $(MFLAGS) -g -c $<

clean:
	rm -f dmemory.o libdmemory.so exceptions.o test.o list.o test
